name: dswitch
version: 0.9.2
description: DSwitch is a cli tool that allows you to rapidly switch between channels and versions of Dart. If you are a flutter user then you are better of using FVM as FVM changes the version of dart embedded in Flutter. DSwitch is intended to help manage a standalone version of Dart if you are doing things like building cli applications. DSwitch can switch between dart channels as well as versions within those channels.
repository: https://github.com/bsutton/dswitch
environment: 
  sdk: '>=2.9.0 <3.0.0'
dependencies: 
  archive: ^2.0.13
  args: ^1.0.0
  dcli: ^0.39.0
  path: ^1.0.0
  pub_semver: ^1.4.4
  settings_yaml: ^2.1.3
dev_dependencies: 
  pedantic: ^1.0.0
  test: ^1.15.0
executables: 
  dswitch: 
