name: dswitch
version: 4.3.9
homepage: https://dswitch.onepub.dev
documentation: https://dswitch.onepub.dev
description: DSwitch is a cli tool that allows you to rapidly switch between channels and versions of Dart. You can also pin a channel to a specific version.
repository: https://github.com/onepub-dev/dswitch
environment: 
  sdk: '>=2.12.1 <3.0.0'
dependencies: 
  archive: ^3.1.2
  args: ^2.1.1
  dcli: 1.20.1
  dcli_core: 1.20.1
  meta: ^1.0.0
  path: ^1.0.0
  pub_semver: ^2.0.0
  pubspec: ^2.0.1
  scope: ^2.2.1
  settings_yaml: ^3.0.4
  system_info: ^1.0.0
dev_dependencies: 
  lint_hard: ^1.0.1
  mocktail: ^0.2.0
  test: ^1.15.0
executables: 
  dswitch: 
  dswitch_install: 
