name: dswitch
version: 3.0.0
description: DSwitch is a cli tool that allows you to rapidly switch between channels and versions of Dart. You can also pin a channel to a specific version.
repository: https://github.com/bsutton/dswitch

# For dswitch to be useful we MUST support older versions dart
# hence we can't ship a null safe version.
environment: 
  sdk: '>=2.6.0 <3.0.0'
dependencies: 
  archive: ^2.0.0
  args: ^1.0.0
  dcli: ^0.41.0
  meta: ^1.0.0
  path: ^1.0.0
  pub_semver: ^1.0.0
  settings_yaml: ^2.0.0
  system_info: ^0.1.0
dev_dependencies: 
  pedantic: ^1.0.0
  test: ^1.15.0
executables: 
  dswitch: 
