name: dswitch
version: 4.2.10
homepage: https://www.noojee.dev
documentation: https://dswitch.noojee.dev
description: DSwitch is a cli tool that allows you to rapidly switch between channels and versions of Dart. You can also pin a channel to a specific version.
repository: https://github.com/noojee/dswitch
environment: 
  sdk: '>=2.12.1 <3.0.0'
dependencies: 
  archive: ^3.1.2
  args: ^2.1.1
  dcli: ^1.9.4
  meta: ^1.0.0
  path: ^1.0.0
  pub_semver: ^2.0.0
  pubspec: ^2.0.1
  settings_yaml: ^3.0.4
  system_info: ^1.0.0
dev_dependencies: 
  lints: ^1.0.1
  mocktail: ^0.1.4
  test: ^1.15.0
executables: 
  dswitch: 
  dswitch_install: 
