name: dswitch
version: 0.0.2
description: A cli tool to rapidly switch between versions of dart.
repository: https://github.com/bsutton/dswitch
environment: 
  sdk: '>=2.9.0 <3.0.0'
dependencies: 
  archive: ^2.0.13
  args: ^1.0.0
  dcli: ^0.37.0
  path: ^1.0.0
  pub_semver: ^1.4.4
  settings_yaml: ^2.1.3
dev_dependencies: 
  pedantic: ^1.0.0
  test: 1.15.4
executables: 
  dswitch: 
