name: dswitch
version: 2.0.1
description: DSwitch is a cli tool that allows you to rapidly switch between channels and versions of Dart. You can also pin a channel to a specific version.
repository: https://github.com/bsutton/dswitch
environment: 
  sdk: '>=2.6.0 <3.0.0'
dependencies: 
  archive: ^2.0.13
  args: ^1.0.0
  dcli: ^0.41.0
  path: ^1.0.0
  pub_semver: ^1.4.4
  settings_yaml: ^2.1.3
  system_info: ^0.1.3
dev_dependencies: 
  pedantic: ^1.0.0
  test: ^1.15.0
executables: 
  dswitch: 
